wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686944519.284234
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.8
      5: 0.15.4
      8:
      - 4
      - 5
